meta-debian/meta-debian

README

Signed-off-by: CongNT <cong.nguyenthe@toshiba-tsdv.com>

README: Add latest testing commit ID for poky

---

recipes-debian/xorg-app/xeyes.bb

Add recipe of xeyes.
Unfortunately, this recipe haven't reviewed yet.
Signed-off-by: Takuya Tominaga <takuya1.tominaga@toshiba.co.jp>

Added Recipe: xorg-apps/xeyes

---

recipes-debian/adduser/adduser_debian.bb
recipes-debian/glib-2.0/files/add-march-i486-into-CFLAGS-automatically.patch
recipes-debian/glib-2.0/files/configure-libtool.patch
recipes-debian/glib-2.0/files/fix-conflicting-rand.patch
recipes-debian/glib-2.0/files/glib-2.0-configure-readlink.patch
recipes-debian/glib-2.0/files/glib-gettextize-dir.patch
recipes-debian/glib-2.0/files/ptest-paths.patch
recipes-debian/glib-2.0/files/run-ptest
recipes-debian/glib-2.0/files/uclibc.patch
recipes-debian/glib-2.0/glib-2.0_debian.bb
recipes-debian/kexec-tools/kexec-tools_debian.bb
recipes-debian/libpcre/libpcre_debian.bb
recipes-debian/libtimedate-perl/libtimedate-perl_debian.bb
recipes-debian/ltrace/files/configure-allow-to-disable-selinux-support.patch
recipes-debian/ltrace/ltrace_debian.bb
recipes-debian/mklibs/mklibs-native_debian.bb
recipes-debian/nss/nss_debian.bb
recipes-debian/openipmi/openipmi_debian.bb
recipes-debian/qemu/files/qemu-enlarge-env-entry-size.patch
recipes-debian/qemu/qemu_debian.bb
recipes-debian/readline/files/acinclude.m4
recipes-debian/readline/readline_debian.bb
recipes-debian/sqlite/sqlite3_debian.bb

- Refine recipes in daisy branch
- Fix sqlite-native recipe

Weekly merging commit

---

recipes-debian/bzip2/bzip2_debian.bb
recipes-debian/coreutils/coreutils_debian.bb
recipes-debian/gnome/gnome-common_debian.bb
recipes-debian/gtk+/gtk+.inc
recipes-debian/krb5/krb5_debian.bb
recipes-debian/libprelude/files/libprelude-dont-regenerate-perl-makefile.patch
recipes-debian/libprelude/files/libprelude-fix-uid-gid-conflicting-types.patch
recipes-debian/libprelude/files/libprelude-perl-build-with-gnu-hash.patch
recipes-debian/libprelude/libprelude_debian.bb
recipes-debian/neon/neon.inc
recipes-debian/samhain/samhain_debian.bb
recipes-debian/xorg-app/rgb_debian.bb
recipes-debian/xorg-proto/presentproto_debian.bb

Weekly merging commit.

---

classes/debian-package-ng.bbclass

These patches provide the function to download and expansion Debian source packages using the snapshot.debian.org API.

Support Snapshot.d.o API

---

classes/debian-package-ng.bbclass

These PRs add the following functions.
- asc file support.
- naming support for SRC_URI
- multi component support

Update Snapshot.d.o support

---

conf/distro/deby.conf
docker/Makefile
recipes-debian/binutils/binutils.inc
recipes-debian/binutils/binutils/0006-Use-libtool-2.4.patch
recipes-debian/binutils/binutils/0012-Add-support-for-Netlogic-XLP.patch
recipes-debian/glibc/glibc/0003-nativesdk-glibc-Raise-the-size-of-arrays-containing-.patch
recipes-debian/glibc/glibc/0004-nativesdk-glibc-Allow-64-bit-atomics-for-x86.patch
recipes-debian/glibc/glibc/0011-eglibc-run-libm-err-tab.pl-with-specific-dirs-in-S.patch
recipes-debian/glibc/glibc/0022-eglibc-Forward-port-cross-locale-generation-support.patch
recipes-debian/glibc/glibc/0025-locale-fix-hard-coded-reference-to-gcc-E.patch
recipes-debian/glibc/glibc/0028-bits-siginfo-consts.h-enum-definition-for-TRAP_HWBKP.patch
recipes-debian/glibc/glibc_debian.bb
recipes-debian/perl/perl_debian.bb
recipes-debian/quilt/quilt_debian.bb
recipes-debian/rdma-core/rdma-core_debian.bb

Now, meta-debian can be built with Poky rev `f4a270a519a14652b7c13a151068b4ef255710e7`.

[master] Update recipes to work with the latest Poky branch master

---

doc/2.components.md

Correct typo and format and add a note about BPN.

[master] Update documentation

---

doc/4.bsp/4.1.bbb.md
doc/4.bsp/4.2.pi.md

Update BSP building manual for branch warrior.

doc/4.bsp: Update manual for branch warrior

---

recipes-debian/libxres/libxres_debian.bb
recipes-debian/tzdata/tzdata_debian.bb
recipes-debian/xorg-xserver/xserver-xorg_debian.bb

Also, update version for tzdata.

[morty] Update build dependencies for libxres and xserver-xorg

---

classes/debian-source.bbclass
conf/layer.conf
recipes-debian/glibc/glibc_debian.bb
recipes-debian/qemu/qemu/0001-egl-headless-add-egl_create_context.patch
recipes-debian/shadow/shadow_debian.bb

qemu: After Poky update qemu to 3.1.1, it dropped some patches of 3.1.0. Re-added missing patch.

Update qemu, shadow and glibc

---

recipes-debian/python/python3_debian.bb

From Poky rev: cd8a048b620b04dcaa7969d70684bcad243ccc58

python3: add tk-lib as runtime dependency for python-tkinter

---

recipes-debian/meson/meson.inc

This backports the following poky's commits:
5c9a02ed678f2a26a26c6398c2837fbd2ddcb561
06606fd9e0c1000c7479f2899eb6e5c48fa5b2cd

meson: backport more patches from poky

---

docker/Makefile
recipes-debian/libpcap/libpcap/0001-pcap-usb-linux.c-add-missing-limits.h-for-musl-syste.patch
recipes-debian/libpcap/libpcap_debian.bb
recipes-debian/openbios/openbios-ppc-native_debian.bb
recipes-debian/python/python-native/0001-python-native-fix-one-do_populate_sysroot-warning.patch
recipes-debian/python/python/builddir.patch

- Add missing patches after Poky update.
- Fix openbios-ppc-native.

[warrior] Weekly update

---

recipes-debian/cmake/cmake.inc

cmake: Define CMAKE_MAJOR_VERSION

---

recipes-debian/glusterfs/glusterfs_debian.bb
recipes-debian/heimdal/heimdal_debian.bb
recipes-debian/libpam-krb5/libpam-krb5.inc
recipes-debian/requests/python3-requests_debian.bb
recipes-debian/vlan/vlan_debian.bb

Fix the issues on meta-debian: #260, #261, #262, #264

Recipes: fix bitbake failed

---

classes/debian-multiarch.bbclass
recipes-bootloader/u-boot/u-boot-mkimage_git.bb
recipes-debian/confuse/confuse_debian.bb
recipes-debian/glusterfs/glusterfs_debian.bb
recipes-debian/memtest86+/memtest86+_debian.bb
recipes-debian/memtest86/memtest86_debian.bb

Fix the issues: #279 , #281 , #282 , #283 , #284

Morty: Update recipes u-boot-mkimage, memtest86*, confuse, glusterfs, debian-multiarch.bbclass

---

recipes-debian/qrencode/qrencode_debian.bb
recipes-debian/setserial/setserial_debian.bb

Hi,
I created the recipes for qrencode and setserial packages. Please check and let me know if you have any problem.
Thanks and BRs,
Hieu

Morty: Add recipes for qrencode, setserial

---

recipes-debian/xinput-calibrator/xinput-calibrator_debian.bb

xinput-calibrator: Generic touchscreen calibration program for X.Org

xinput-calibrator: Add new recipe

---

recipes-debian/minizip/minizip_debian.bb
recipes-debian/xorg-util/gccmakedep_debian.bb
recipes-debian/xorg-util/imake_debian.bb
recipes-debian/xorg-util/lndir_debian.bb
recipes-debian/xorg-util/makedepend_debian.bb
recipes-debian/xorg-util/util-macros_debian.bb
recipes-debian/xorg-util/xorg-cf-files_debian.bb
recipes-debian/xorg-util/xorg-util-common.inc
recipes-debian/xorg-util/xutils-dev_debian.bb

Add recipes for minizip, xutils-dev (xutils-dev, gccmakedep, imake, lndir, xorg-cf-files)

Add new recipes for xutils-dev and minizip packages
