- recipes-debian/openssl/openssl_debian.bb
By following the instructions in the README, the daisy branch of poky that is pulled from Yocto's repository has the required openssl recipe filename of `openssl_1.0.1m.bb` instead of `openssl_1.0.1j.bb`, which meta-debian attempts to find ([link](http://git.yoctoproject.org/clean/cgit.cgi/poky/tree/meta/recipes-connectivity/openssl?h=daisy)).
> Update openssl path for poky branch daisy

- recipes-debian/binutils/files/binutils-xlp-support_debian.patch
Modify binutils-xlp-support_debian.patch so it can work
with new commit of poky.
Signed-off-by: CongNT <cong.nguyenthe@toshiba-tsdv.com>
> binutils: fix error patch can not apply

- recipes-core/packagegroups/packagegroup-core-boot.bbappend
- recipes-debian/dpkg/dpkg-update-alternatives_debian.bb
- recipes-debian/dpkg/files/fix_offline_dir.patch
- recipes-debian/dpkg/files/fix_update_alternatives_dir.patch
- recipes-debian/dpkg/files/implement-offline-mode.patch
Apply patches from upstream for offline mode of dpkg as in:
https://lists.debian.org/debian-dpkg/2014/08/msg00052.html
To avoid modify poky source code, OFFLINE_ROOT will be used
instead of DPKG_INSTDIR.
Signed-off-by: CongNT <cong.nguyenthe@toshiba-tsdv.com>
> dpkg: Add patches for supporting offline mode

- recipes-debian/dpkg/files/fix_update_alternatives_dir.patch
Correct install path of dpkg-update-alternative.
Signed-off-by: CongNT <cong.nguyenthe@toshiba-tsdv.com>
> dpkg-update-alternative: Fix install dir

- recipes-debian/automake/automake_debian.bb
- recipes-debian/libcap/libcap_debian.bb
- recipes-debian/openssl/openssl_debian.bb
The code in native.bbclass in meta adds -native suffix
to the package names that don't have it. perl-native-runtime
becomes perl-native-runtime-native because of this.
Renamed perl-native-runtime -> hostperl-runtime-native to avoid
mangling it and to conform with the naming convetion for native
packages.
(From meata, master branch, commit 675ff42c6030b33ff49dd2ec5ff9d157f23b48dc )
Signed-off-by: Hoang Trong Nghia <nghia.hoangtrong@toshiba-tsdv.com>
> meta-debian: rename perl-native-runtime

- recipes-kernel/linux/linux-base_git.bb
The patch (from meta, branch master, commit c0e9f2d)
sets ARCH i386 or x86_64 explicitly to configure task
to avoid this host contamination. So kernel configuration step
is also changed so that it can map i386 and x64 back to arch/x86.
Signed-off-by: Hoang Trong Nghia <nghia.hoangtrong@toshiba-tsdv.com>
> linux-base: Mapping between i386/x86_64 and x86 for kernel ARCH

- README.md
A change directory is needed before `setup build directory`. This patch fix:
```
bash: ./poky/oe-init-build-env: No such file or directory
```
> Update README.md cd before setup build dir

- recipes-debian/autotools-dev/autotools-dev_debian.bb
- recipes-debian/dbus/dbus_debian.bb
- recipes-debian/gconf/files/add_option_change_root_path.patch
- recipes-debian/gconf/gconf_debian.bb
- recipes-debian/lxc/lxc_debian.bb
- recipes-debian/nss/files/nss-regen-chk.init
- recipes-debian/nss/files/nss-regen-chk.service
- recipes-debian/nss/nss_debian.bb
After removed dpkg-configure.service, we re-checked all of postinsts in recipe to make sure they still can work correctly.
> Make postinst run at do_rootfs and the first boot

- recipes-kernel/linux/files/qemuarm.config
When we follow the README.md to build a minimal OS for qemuarm.
The booting is hung after messages:
| VFS: Mounted root (ext4 filesystem) on device 254:0.
| Freeing unused kernel memory: 140K
| mkdir: can't create directory '/dev/pts': File exists
| random: nonblocking pool is initialized
The DEVTMPFS_MOUNT is not enabled by default in kernel defconfig
for arm. So, add enabling the config to qemuarm.config file to
automatically mount the devtmpfs filesystem at /dev.
Signed-off-by: Hoang Van Tuyen <tuyen.hoangvan@toshiba-tsdv.com>
> kernel:qemuarm: Enable DEVTMPFS_MOUNT

- conf/distro/deby.conf
- recipes-debian/tzdata/tzdata_debian.bb
Since '1da8f52', poky has converted package_qa_check_license to use standard QA check
configuration interface through package_qa_handle_error.
If we want to see license-checksum's error message during bitbake-ing,
we need to add it to ERROR_QA.
> Add "license-checksum" to ERROR_QA

- classes/debian-source.bbclass
- conf/layer.conf
Currently, debian-source.bbclass get the path of layer meta-debian as
'poky/meta-debian'. This is not a good implementation if user wants to put
meta-debian in a different path or rename the folder name.
Make it be flexible by using LAYERDIR to get the layer path.
> debian-source.bbclass: Make class flexible to get layer path of meta-debian

- classes/debian-source.bbclass
By processing debian-source.bbclass, the file name is specified for the tag of
the file path in SRC_URI. If tilde (~) is included in the file name, tilde (~)
can not be used for the tag, so it fails in tag processing of the file.
This replace to underscore (_) if the tilde is included in the tag.
Signed-off-by: Nobuhiro Iwamatsu <nobuhiro.iwamatsu@miraclelinux.com>
> debian-source: Add character replacement function used in name tag

- classes/debian-source.bbclass
I'd like to disable debian-source by default to keep meta-debian stable for users.
debian-source should only be enabled on development environments.
For developers and maintainers, to enable it, just change `DEBIAN_SOURCE_ENABLED` to "1" in `build-dir/conf/local.conf`.
> [master] debian-source.bbclass: Disable debian-source by default

- classes/debian-package.bbclass
In the Debian source package, debian/patches directory may be empty, or
debian/parches/series with no data.
The current process checks the contents of DEBIAN_QUILT_PATCHES and the
existence of a directory, but in the above case an error occurs.
This fix switched to the check process of debian/parches/series file.
Signed-off-by: Nobuhiro Iwamatsu <nobuhiro.iwamatsu@miraclelinux.com>
> debian-package.bbclass: Update checking DEBIAN_QUILT_PATCHES

- classes/debian-package.bbclass
The '/archive' is not necessary for JSON files.
> debian-package.bbclass: Fix wrong URL assembly for snapshot.d.o

- classes/linux-src.bbclass
- conf/distro/deby.inc
There was actually no way to specify a commit hash of kernel repository.
LINUX_GIT_SRCREV was used as branch name in SRC_URI, so 'fetch' of the
kernel failed if we specified the commit hash in LINUX_GIT_SRCREV.
This patch adds new variable LINUX_GIT_BRANCH to specify branch name and
makes LINUX_GIT_SRCREV to be used only for SRCREV.
> linux-src.bbclass: support kernel commit hash in LINUX_GIT_SRCREV

- recipes-debian/flex/flex_debian.bb
Fix undefined reference to `reallocarray'
by disabling reallocarray.
reference:
https://github.com/buildroot/buildroot/commit/ffbd8dfb8a1fcbc0cb209f8ede4841c543524525
> recipes-debian/flex: Disable reallocarray

- recipes-debian/glibc/glibc-locale_debian.bb
Since commit 53b3e8c9d6e34f076a006df41cd2854b3cb30c71,
meta/recipes-core/glibc/glibc-common.inc set PV in the file.
So, if meta-debian and poky use different glibc versions, glibc-locale
package vesion will be set to Poky's glibc version.
```
$ bitbake-layers show-recipes | grep -A3 glibc
glibc:
meta-debian          2.28
meta                 2.29
glibc-locale:
meta-debian          2.29
meta                 2.29
```
In the case, glibc-locale package's PV is 2.29, but the package is
created from glibc 2.28 package.
This patch recipes-debian/sources/glibc.inc file to re-set PV to
debian glibc version.
> glibc-locale: overwrite default PV

- conf/distro/deby.inc
"bitbake -c populate_sdk core-image-minimal" automatically adds packages from
image package list to SDK package list.
This can cause a conflict if image package list and target-sdk-provides-dummy
provide same packages.
Temporarily avoid this problem by remove target-sdk-provides-dummy out of
TOOLCHAIN_TARGET_TASK.
Upstream bug: https://bugzilla.yoctoproject.org/show_bug.cgi?id=13338
> deby.inc: Fix the conflict when build SDK with "-c populate_sdk"

- recipes-kernel/linux/files/powerpc-Disable-attribute-alias-warnings-from-gcc8.patch
- recipes-kernel/linux/files/powerpc-ptrace-Disable-array-bounds-warning-with-gcc.patch
The code in Makefile has been changed, update patches to avoid conflict.
> linux-base: Refresh patches for v4.19.60-cip7

- recipes-debian/busybox/busybox_debian.bb
This PR contains 3 commits to fix test errors. 
Every commit added a patch name to SRC_URI variable because Poky has a patch. So it didn't needed to write a new patch to fix test errors.
The 0001-testsuite-check-uudecode-before-using-it.patch for tar command test , 0001-du-l-works-fix-to-use-145-instead-of-144.patch for du command test, and 0001-dc.tests-fix-two-test-case-to-also-depend-on-DC_BIG.patch for dc command test.
> busybox: Add ptest failures fix patches

- recipes-debian/openssl/openssl_debian.bb
OpenSSL's ptest failed by following errors.
```
test/recipes/90-test_shlibload.t ..
1..10
Failed to load libcrypto
../util/shlib_wrap.sh ./shlibloadtest -crypto_first ../libcrypto.so.1.1 ../libssl.so.1.1 /tmp/w5Gepyd2VU => 1
not ok 1 - running shlibloadtest -crypto_first /tmp/w5Gepyd2VU
not ok 2
Failed to load libssl
```
Test test/recipes/90-test_shlibload.t runs following command.
```
../util/shlib_wrap.sh ./shlibloadtest -crypto_first ../libcrypto.so.1.1 ../libssl.so.1.1 /tmp/w5Gepyd2VU => 1
```
This test uses libcrypto.so.1.1 and libssl.so.1.1 for tests which are in /usr/lib/openssl/ptest/ but
we have libcrypto.so and libssl.so in the directory not libcrypto.so.1.1 and libssl.so.1.1.
It seems it is the root cause of test failure.
Therefore in the do_install_ptest(), create symbolic …
> openssl: ptest: Do not change target file name

- recipes-debian/gawk/gawk_debian.bb
When run ptest, "include" test is failed.
I found poky and meta-debian do_install_ptest() are bit differrent[1].
Therefore updated do_install_ptest() recipe like poky.
The gawk's ptest success with this patch.
1:https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-extended/gawk/gawk_4.2.1.bb?h=warrior&id=fdfdd899451674f1756f441fd0bf03a7b0f138aa
> gawk: ptest: update do_install_ptest() recipe

- recipes-debian/glibc/glibc_debian.bb
Follow-up for poky's commit b174d936e91902c3e2ab800856bb7bc492d096a0.
The commit removes `do_poststash_install_cleanup()` task. So the `_append()` does not remove empty /usr/share any more.
> glibc: update way to remove empty /usr/share

- recipes-debian/base-files/base-files_debian.bb
- recipes-debian/base-passwd/base-passwd_debian.bb
- recipes-debian/bash/bash_debian.bb
- recipes-debian/dbus/dbus-test_debian.bb
- recipes-debian/quilt/quilt_debian.bb
- recipes-debian/shadow/shadow_debian.bb
- base-files: Install a default '/etc/shells' with '/bin/sh' as a valid login shell.
- base-passwd: Remove redundant spaces in '/etc/passwd' and '/etc/group'.
- dbus-test: Package 'dbus-test' is empty, make 'dbus-test-ptest' depend on 'dbus' instead.
- quilt: Make 'quilt-ptest' depend on 'quilt'.
> [warrior] Update and fix bug

- recipes-debian/openssl/openssl_debian.bb
Set OPENSSL_ENGINES to the path where engines are actually installed.
From Poky rev: 77a4470733a79b1d13e2848b52523d95440164eb
> openssl: make OPENSSL_ENGINES match install path

- recipes-debian/perl/perl_debian.bb
This reverts commit 7dedd80ff47de4ed88b637c32ed2b3aba1965c3f.
This test depends on target machine performance.
On a weak machine, we just need to increase test timeout
by 'export PERL_TEST_TIME_OUT_FACTOR=2' (or greater) when run ptest.
> [warrior] Revert "perl: fix ptest timeout failure"

- recipes-debian/ipxe/ipxe_debian.bb
When invoke 'bitbake world -c cleanall' for aarch64, then it fails as syslinux is not provided and ipxe depends on syslinux.
> ipxe: build only for x86 or x86_64 target

- recipes-debian/perl/perl_debian.bb
The packages were added by 7dedd80ff47de4ed88b637c32ed2b3aba1965c3f, and removed by c87f4cc5fd8fb87d99ebcd8094567f9df3b987d7.
> perl: re-add some dependent packages for ptest

- recipes-debian/meson/meson.inc
Reuse the patch from layer "meta":
(0001-Handle-strings-in-cross-file-args.-Closes-4671.patch)
This allows <language>_args and <language>_link_args properties, e.g.,
c_link_args, in meson.cross to be specified as either a string or a
list.
(From meta:warrior: 8855a1ec4de0762038590ff06355af7ba8beea29)
Signed-off-by: Nguyen Van Hieu <hieu.nguyenvan@toshiba-tsdv.com>
> meson: Handle strings in cross file args

- recipes-debian/tcpdump/tcpdump/add-ptest.patch
- recipes-debian/tcpdump/tcpdump/avoid-absolute-path-when-searching-for-libdlpi.patch
- recipes-debian/tcpdump/tcpdump/run-ptest
- recipes-debian/tcpdump/tcpdump/unnecessary-to-check-libpcap.patch
- recipes-debian/tcpdump/tcpdump_debian.bb
Import changes from meta-openembedded's
meta-networking/recipes-support/tcpdump/tcpdump_4.9.3.bb
(commit a24acf94d48d635eca668ea34598c6e5c857e3f8)
Signed-off-by: Atsushi Nemoto <atsushi.nemoto@sord.co.jp>
> tcpdump: bump the upstream version to 4.9.3-1~deb8u1

- recipes-debian/glibc/glibc_debian.bb
- recipes-kernel/linux-libc-headers/linux-libc-headers-base_git.bb
Without this, the following code cannot be compiled with the SDK of core-image-minimal.
```
#include <errno.h>
#include <stdio.h>
int main(void)
{
printf("errno = %d\n", errno);
return 0;
}
```
Tested with
```
Build Configuration:
BB_VERSION           = "1.42.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-deby-linux"
MACHINE              = "qemuarm64"
DISTRO               = "deby-tiny"
DISTRO_VERSION       = "10.0"
TUNE_FEATURES        = "aarch64 armv8a crc"
TARGET_FPU           = ""
meta                 
meta-poky            = "warrior:023ff85a9ae94331926e923b346fd8a349881e63"
meta-debian          = "warrior:f396c5441b87530abe2d67d470a2894d341330ce"
```
> linux-libc-headers, glibc: Add linux-libc-headers-dev to glibc-dev

- recipes-debian/openssl/openssl_debian.bb
with openSSL 1.1.1d we start seeing errors like
```
Error Generating Key
139979727451584:error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy:../openssl-1.1.1d/crypto/rand/drbg_lib.c:342:
```
when using openssl from openssl-native on build hosts, this is due to
limiting the random seed to devrandom, to support older hosts, since the
option allows to have a comma separated list of methods to try, we can
try the default first and if that fails then fallback to devrandom, this
will ensure that it keeps working with build systems which dont support
getrandom()
(From OE-Core rev: 8b4edb8552b238680d8dcef565e830a8e28a223c)
(From Poky rev: 53b5654d6eebfbc1e290af3cfda7f0ed7b71f59e)
See also https://www.mail-archive.com/openembedded-core@lists.openembedded.org/msg127 …
> openssl: Enable os option for with-rand-seed as well

- doc/3.development/3.1.create_recipe.md
Security fixes should be handled by Debian source package.
It is better to wait for Debian maintainers decide to apply the fix
or not.
This can avoid conflict between recipe's patches and Debian source package.
> doc: Add notice about not to reuse CVE patches

- doc/5.limitation.md
For now, to keep meta-debian minimal and reduce effort of maintenance,
meta-debian only provides recipes to support PACKAGECONFIG features which are enabled by default.
More recipes may be added in future if there are requests.
> doc/5.limitation.md: Add information about PACKAGECONFIG variation support

- recipes-debian/elfutils/elfutils_debian.bb
Elfutils-Exception no longer exists. The license is now GPLv2/LGPLv3+ for the libraries and GPLv3+ for stand-alone programs.
> elfutils: Correct elfutils licenses

- recipes-debian/libbsd/libbsd_debian.bb
libbsd-0.7.0-2+deb8u1 has added new debian/patches,
so remove the empty DEBIAN_QUILT_PATCHES.
Signed-off-by: Atsushi Nemoto <atsushi.nemoto@sord.co.jp>
> libbsd: Remove the empty DEBIAN_QUILT_PATCHES

- recipes-debian/attr/acl/run-ptest
- recipes-debian/attr/acl_debian.bb
I took a mistake, so I re-created this PR. You can refer the previous one from [here](https://github.com/meta-debian/meta-debian/pull/221).
This ptest is created based on poky's ptest for acl (070ea45b6c).
You can test this PR as follows:
local.conf:
```
DISTRO_FEATURES_append = " ptest"
EXTRA_IMAGE_FEATURES += "ptest-pkgs"
IMAGE_ROOTFS_EXTRA_SPACE = "20480"
```
Run:
```shell
$ ptest-runner acl
```
I have confirmed that the following test case will be failed:
```
FAIL: $ getfacl --omit-header f
FAIL: $ getfacl --omit-header f
FAIL: $ getfacl --omit-header f
FAIL: $ getfacl --omit-header d
FAIL: $ getfacl --omit-header d/d
FAIL: $ getfacl --omit-header d/l
FAIL: $ getfacl --omit-header d/d
FAIL: $ getfacl --omit-header d/d
FAIL: $ getfacl --omit-header d
FAIL: $ getfacl --omit-header d …
```
> Add ptest for acl

- recipes-debian/glibc/glibc_debian.bb
When set DEBUG_BUILD="1" to local.conf, got following build error.
```
| make[2]: ***
[/home/masami/metadebian/build/tmp/work/aarch64-deby-linux/glibc/2.28-r0/build-aarch64-deby-linux/posix/regex.o]
Error 1
| make[2]: *** Waiting for unfinished jobs....
| In file included from regex.c:72:
| regexec.c: In function 'check_node_accept_bytes':
| regexec.c:3833:29: error: 'extra' may be used uninitialized in this
function [-Werror=maybe-uninitialized]
|         const unsigned char *coll_sym = extra + cset->coll_syms[i];
|                              ^~~~~~~~
| cc1: all warnings being treated as errors
| ../o-iterator.mk:9: recipe for target
'/home/masami/metadebian/build/tmp/work/aarch64-deby-linux/glibc/2.28-r0/build-aarch64-deby-linux/posix/regex.os'
failed
| make[2]: *** …
```
> glibc: Fix build error when set DEBUG_BUILD="1"

- recipes-debian/dosfstools/dosfstools_debian.bb
dosfstools_3.0.27-1+deb8u1 has added new debian/patches,
so remove the empty DEBIAN_QUILT_PATCHES.
Signed-off-by: Atsushi Nemoto <atsushi.nemoto@sord.co.jp>
> dosfstools: Remove the empty DEBIAN_QUILT_PATCHES

- recipes-debian/diffutils/diffutils_debian.bb
Without perl, got following error.
```
============================================================================
make[1]: *** [Makefile:1554: test-suite.log] Error 1
make[1]: Leaving directory '/usr/lib/diffutils/ptest/tests'
make: *** [Makefile:1662: check-TESTS] Error 2
make: Leaving directory '/usr/lib/diffutils/ptest/tests'
ERROR: Exit status is 512
DURATION: 20
```
Add pers to RDEPENDS_${PN}-ptest, it works fine.
```
============================================================================
make[1]: Leaving directory '/usr/lib/diffutils/ptest/tests'
make: Leaving directory '/usr/lib/diffutils/ptest/tests'
DURATION: 21
END: /usr/lib/diffutils/ptest
2020-06-08T00:24
STOP: ptest-runner
```
> diffutils: Add perl to ptest environment

- recipes-debian/gcc/gcc-cross-canadian_debian.bb
- recipes-debian/gcc/gcc-cross-initial_debian.bb
- recipes-debian/gcc/gcc-cross_debian.bb
- recipes-debian/gcc/gcc-crosssdk-initial_debian.bb
- recipes-debian/gcc/gcc-crosssdk_debian.bb
- recipes-debian/gcc/gcc-runtime_debian.bb
- recipes-debian/gcc/gcc-sanitizers_debian.bb
- recipes-debian/gcc/gcc_debian.bb
- recipes-debian/gcc/libgcc_debian.bb
gcc* use same shared source code. It will fail to find gcc source if PRs are not same.
> [morty] gcc*: Stop separating PRs for gcc* recipes

- recipes-debian/valgrind/valgrind_debian.bb
valgrind uses `uname -r` for checking kernel version.
This makes it failed to build on host system with old kernel.
Replace `uname -r` with the built kernel version in sysroot.
> [morty] valgrind: Avoid checking kernel version on host machine

- recipes-debian/base-files/base-files_debian.bb
Fix do_install failure ("cannot create .../image/usr/lib64/os-release:
Directory nonexistent") with non-standard ${libdir} value.
Signed-off-by: Atsushi Nemoto <atsushi.nemoto@sord.co.jp>
> base-files: fix build failure with multilib

- recipes-debian/util-linux/util-linux_debian.bb
util-linux's ptest use xz option to unarchive tar file but busybox's tar doesn't
support it. Add tar package for run ptest.
```
SKIP:       losetup: losetup-loop                   (missing scsi_debug module (dry-run))
tar: unrecognized option '--xz'
BusyBox v1.30.1 (2020-09-10 04:12:26 UTC) multi-call binary.
Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]...
ls: cannot access '/usr/lib/util-linux/ptest/tests/output/lsblk/dumps/simple-lvm/*.cols': No such file or directory
tar: unrecognized option '--xz'
BusyBox v1.30.1 (2020-09-10 04:12:26 UTC) multi-call binary.
Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]...
ls: cannot access '/usr/lib/util-linux/ptest/tests/output/lsblk/dumps/simple-nvme/*.cols': No such file or …
```
> util-linux: add tar for ptest

- recipes-debian/syslog-ng/syslog-ng_debian.bb
Add syslog-ng-mod-journal library as an optional package
and can be included in the target image by specifying in local.conf
`IMAGE_INSTALL_append = " syslog-ng-mod-journal"`
Signed-off-by: venkata pyla <venkata.pyla@toshiba-tsip.com>
> syslog-ng-mod-journal: add mod-journal binary package

- recipes-debian/libxml/libxml2_debian.bb
libxml2 package contains xmlcatalog and xmllint commands, which should be provided by libxml2-utils package.
```
masami@ubuntu1804:~/metadebian/build$ ls tmp/work/aarch64-deby-linux/libxml2/2.9.4-r0/packages-split/libxml2/usr/
./  ../  bin/  lib/
masami@ubuntu1804:~/metadebian/build$ ls tmp/work/aarch64-deby-linux/libxml2/2.9.4-r0/packages-split/libxml2/usr/bin/
./  ../  xmlcatalog*  xmllint*
masami@ubuntu1804:~/metadebian/build$ ls tmp/work/aarch64-deby-linux/libxml2/2.9.4-r0/packages-split/libxml2-utils/
./  ../
```
So, empty libxml2-utils package causes following error when add libxml2-utils to rootfs.
```
ERROR: core-image-minimal-1.0-r0 do_rootfs: Unable to install packages.
Command
'/home/masami/metadebian/build/tmp/work/qemuarm64-deby-linux/core-image-minimal/1.0-r0/recipe-sysroot-n …
```
> libxml: Fix libxml2-utils packaging issue

- classes/debian-cve-check.bbclass
Task cve-check only looks at NVD database.
This class check CVEs with Debian Security Tracker
and pass the fixed CVEs to cve-check as whitelist.
In order to test this class inherit cve-check and this class in the local.conf
and run cve_check task.
Example:
$ bitbake -c cve_check openssl
$ bitbake core-image-minimal
> debian-cve-check.bbclass: add new class

- recipes-debian/fail2ban/fail2ban/fail2ban_setup.py
- recipes-debian/fail2ban/fail2ban_debian.bb
fail2ban build got following error because files added to SRC_URI doesn't exist.
> WARNING: fail2ban-0.10.2-r0 do_fetch: Failed to fetch URL file://fail2ban, attempting MIRRORS if available
ERROR: fail2ban-0.10.2-r0 do_fetch: Fetcher failure: Unable to find file file://fail2ban anywhere.
So, use `debian-initd` in source package as init script.
I tried to build by `setup.py` in source package as suggested in #238 .
But its failed because default `setup.py` makes symlink to host's python interpreter.
To avoid this, add `fail2ban_setup.py` as meta-security does.
This file and `setup.py `suggested in #238 are the same.
The main changes in `fail2ban_setup.py` are the removal of the 2 classes and the obsolete files checking process.
The 2 classes are for creating symlinks and supporting options …
> fail2ban: fix build error

- classes/debian-cve-check.bbclass
debian-cve-check include update process of CVE information from Debian Security Tracker.
There is timestamp check to prevent multiple download.
However, if the task execute at the same time in parallel, pass timestamp checking and 
json file is downloaded multiple times.
To fix this, move json update process after do_populate_cve_db.
> debian-cve-check.bbclass: Fix multiple download

- recipes-debian/python-cryptography/files/use-hazmat-module-from-native.patch
- recipes-debian/python-cryptography/python-cryptography_debian.bb
Use hazmat module from python-cryptography-native
to avoid importing error:
| ImportError: wrong ELF class: ELFCLASS32
Fix #256
> python-cryptography: correct build dependency

- recipes-debian/openssl/openssl_debian.bb
When use mv command in do_package(), it preserves UID and GID.
According to yocto manual[1], it recommends to use install command or
cp with --no-preserve option to not preserve UID/GID. So to fix host-user-contaminated issue[2], use install and cp command instead of mv.
When mv command is used,  uid 1000 owned ./etc/ssl/certs,  ./etc/ssl/private/, and ./etc/ssl/openssl.cnf.
```
masami@debian:~/meta-debian/build$ dpkg-deb -c tmp/work/aarch64-deby-linux/openssl/1.1.1d-r0/deploy-debs/aarch64/openssl-conf_1.1.1d-r0_arm64.deb 
drwxrwxrwx root/root         0 2021-04-02 09:00 ./
drwxr-xr-x root/root         0 2021-04-02 09:00 ./etc/
drwxr-xr-x root/root         0 2021-04-02 09:00 ./etc/ssl/
-rw-r--r-- 1000/1000     11118 2021-04-02 09:00 ./etc/ssl/openssl.cnf
masami@debian:~/meta-debian/build$ …
```
> openssl: Fix QA issue host-user-contaminated

- recipes-debian/libbsd/libbsd_debian.bb
This PR fix following error.
```
ERROR: libbsd-0.9.1-r0 do_debian_patch: DEBIAN_QUILT_PATCHES is null, but /home/masami/metadebian/build/tmp/work/aarch64-deby-linux/libbsd/0.9.1-r0/libbsd-0.9.1/debian/patches/series exists
ERROR: libbsd-0.9.1-r0 do_debian_patch: Please consider to redefine DEBIAN_QUILT_PATCHES
ERROR: libbsd-0.9.1-r0 do_debian_patch: Function failed: do_debian_patch (log file is located at /home/masami/metadebian/build/tmp/work/aarch64-deby-linux/libbsd/0.9.1-r0/temp/log.do_debian_patch.1062)
ERROR: Logfile of failure stored in: /home/masami/metadebian/build/tmp/work/aarch64-deby-linux/libbsd/0.9.1-r0/temp/log.do_debian_patch.1062
ERROR: Task (/home/masami/metadebian/poky/meta-debian/recipes-debian/libbsd/libbsd_debian.bb:do_debian_patch) failed with exit code '1'
```
New …
> libbsd: Fix libbsd build error

- recipes-debian/bsdmainutils/bsdmainutils_debian.bb
Hi, 
The do_install wil fail if missing group "tty":
| chown root:tty /tmp/work/i586-deby-linux/bsdmainutils/9.0.6-r0/image/usr/bin/bsd-write
| chown: invalid group: ‘root:tty’
should be add dependency on base-passwd package
> bsdmainutils: Add missing dependency on base-passwd

- recipes-debian/xorg-util/imake_debian.bb
- recipes-debian/xorg-util/lndir_debian.bb
The "imake" and "lndir" do not require to install "xproto" package
(follow the debian/control)
> imake/lndir: remove rdepends on "xproto"

- recipes-debian/pseudo/pseudo/0001-don-t-renameat2-please.patch
- recipes-debian/pseudo/pseudo_debian.bb
Some packages, e.g. coreutils/gawk, use install-sh script(which is related to automak command) install softwares during install process. It uses mv command to move files. In poky build system, install process is working in fakeroot environment. This fakeroot environment is created by pseudo package.  However, package which use install-sh script got host-user-contaminated warning from poky in do_package_qa process. It seems main cause is using mv command during install process which may break fakeroot environment.
I checked poky but it doesn't have same problem. Then I found the differnece between meta-debian and poky is pseudo package version. The poky uses newer revision of pseudo package than debian. 
Finally I found a patch to fix renameat2 problem in upstream[1].  I backported"don't …
> pseudo: Backport bug fix patch from upstream

- recipes-debian/automake/automake_debian.bb
While native building, there is a parallel failure
[snip]
|: && mkdir -p doc && ./pre-inst-env /usr/bin/env perl
../automake-1.16.1/doc/help2man --output=doc/aclocal-1.16.1
aclocal-1.16
|help2man: can't get `--help' info from aclocal-1.16
|Try `--no-discard-stderr' if option outputs to stderr
Makefile:3693: recipe for target 'doc/aclocal-1.16.1' failed
[snip]
Correct Makefile rule to fix the issue
(From OE-Core rev: ef4907f311e3ddedfa3eb8a111cc1d146c19851a)
> automake: fix race in parallel builds

- recipes-debian/fcode-utils/fcode-utils_debian.bb
- recipes-debian/fcode-utils/files/dont-strip-executable-file.patch
- recipes-debian/pam/files/fix-host-gcc-cant-recognized-option-fmacro-prefix-map.patch
- recipes-debian/pam/libpam_debian.bb
Hi,
I created this pull request to improve fcode-utils and libpam recipes, please consider to apply it.
- fcode-utils: 
- should be compile with CC=$CC to support for cross-compile
- Don't strip executable file
- libpam: compile fail when host gcc version below 8.0, it can't recognized option -fmacro-prefix-map.
similar as issue: https://www.yoctoproject.org/pipermail/meta-virtualization/2019-February/004028.html
> Fix libpam and fcode-utils compile error
